### ISSUE TITLE
Incorrect Error Message -  Error while processing the Kafka inbound endpoint Message and the message should be in the format of application/json

### ISSUE THREAD

**Issue by maheeka** [wso2-extensions/esb-inbound-kafka#9]
According to the below code, the above error is thrown even when the issue is not related to message format. 

https://github.com/wso2-extensions/esb-inbound-kafka/blob/b040044e7d061f7e6290f76c6a9d5adebf75d1c9/src/main/java/org/wso2/carbon/inbound/kafka/KafkaMessageConsumer.java#L373

I got this error when I had a problem with my car file causing it to fail deployment. i.e. the error was in finding the injecting sequence and not the content type. 

```
 SequenceMediator seq = (SequenceMediator) this.synapseEnvironment.getSynapseConfiguration()
.getSequence(this.injectingSeq);
```

Stacktrace : 
```
[2018-04-04 15:57:58,434] ERROR - KafkaMessageConsumer Error while processing the Kafka inbound endpoint Message and the message should be in the format of application/json
java.lang.NullPointerException
        at org.wso2.carbon.inbound.kafka.KafkaMessageConsumer.injectMessage(KafkaMessageConsumer.java:364)
        at org.wso2.carbon.inbound.kafka.KafkaMessageConsumer.injectMessage(KafkaMessageConsumer.java:330)
        at org.wso2.carbon.inbound.kafka.KafkaMessageConsumer.consumeKafkaRecords(KafkaMessageConsumer.java:313)
        at org.wso2.carbon.inbound.kafka.KafkaMessageConsumer.poll(KafkaMessageConsumer.java:423)
        at org.wso2.carbon.inbound.endpoint.protocol.generic.GenericTask.taskExecute(GenericTask.java:41)
        at org.wso2.carbon.inbound.endpoint.common.InboundTask.execute(InboundTask.java:51)
        at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:98)
        at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by bhavithadornala** [comment]
This Error also comes when the inbound point cannot find the sequence given.

**Comment by anupama-pathirage** [comment]
Moved the issue to https://github.com/wso2/micro-integrator/issues/3547
